import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://d1k3d9s7og4dh2.cloudfront.net" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://d1k3d9s7og4dh2.cloudfront.net" />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
